/** Build a conservative applicant payload from a Graph/Outlook message. */
interface MailboxValue { emailAddress?: { name?: string; address?: string } }
interface MessageInput { id?: string; internetMessageId?: string; subject?: string; receivedDateTime?: string; webLink?: string; body?: string | { content?: string }; bodyPreview?: string; from?: string | MailboxValue; sender?: string | MailboxValue; attachments?: { name?: string; Name?: string; isInline?: boolean }[]; attachmentText?: string; }
interface ApplicantPayload { [key: string]: string | number }
function text(value: string | undefined): string { return (value || "").trim(); }
function stripHtml(value: string): string { return value.replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim(); }
function unique(values: string[]): string[] { return values.filter((v,i) => v !== "" && values.indexOf(v) === i); }
function urls(source: string, pattern: RegExp): string[] { return unique((source.match(pattern)||[]).map(v => v.replace(/[),.;:!?]+$/g,"").replace(/^www\./i,"https://www."))); }
function evidence(source: string, pattern: RegExp): string { return pattern.test(source) ? "Yes" : ""; }
function likelyResume(name: string): boolean { return /(?:resume|curriculum|(?:^|[_\-.\s])cv(?:[_\-.\s]|$))/i.test(name) && /\.(pdf|docx?|rtf)$/i.test(name); }
function inferName(body: string, subject: string, display: string, email: string): string { const patterns=[/\b[Mm]y name is\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,3})/,/\b[Tt]his is\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,3})/,/\bI am\s+([A-Z][A-Za-z.'-]+(?:\s+[A-Z][A-Za-z.'-]+){1,3})/];for(const pattern of patterns){const found=body.match(pattern);if(found)return found[1].trim();}const clean=subject.replace(/\b(?:re|fw|fwd|application|applying|resume|cv|for|the|position|role|intern|internship|engineer|engineering|developer|job|opening|candidate|ai|ml)\b|[\-_:|/]+/gi," ").replace(/\s+/g," ").trim(); if(/^[A-Za-z.'-]+(?:\s+[A-Za-z.'-]+){1,3}$/.test(clean))return clean; if(display&&!/@/.test(display))return display; return email.split("@")[0].replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()); }
function classify(source: string): string { if(/engineering\s+ai/i.test(source))return "Engineering AI"; if(/ai\s+engineer(?:ing)?\s+(?:intern|internship)/i.test(source))return "AI Engineering Internship"; if(/(?:ai|ml|machine learning).{0,20}(?:intern|internship)|(?:intern|internship).{0,20}(?:ai|ml|machine learning)/i.test(source))return "AI/ML Internship"; if(/(?:ai|ml|machine learning).{0,20}(?:job|position|role)/i.test(source))return "AI/ML Job"; return "Other"; }
function firstMatch(source:string,patterns:RegExp[]):string{for(const pattern of patterns){const match=source.match(pattern);if(match&&match[1])return match[1].trim().replace(/[.;,]+$/g,"");}return "";}
function conciseList(source:string,label:string):string{const pattern=new RegExp(`\\b${label}\\s*[:\\-]\\s*([^|]{3,240}?)(?=\\s+(?:education|degree|branch|college|university|experience|current role|location|skills|projects?|certifications?|github|linkedin|phone|email)\\s*[:\\-]|$)`,"i");const match=source.match(pattern);if(!match)return "";return match[1].replace(/\s*[•\n]+\s*/g,"; ").replace(/\s+/g," ").trim().slice(0,240);}
function bodyContent(value:string|{content?:string}|undefined):string{return typeof value==="string"?value:text(value?.content);}
function mailbox(value:string|MailboxValue|undefined):{name:string;address:string}{if(typeof value==="string"){const bracket=value.match(/^\s*([^<]+?)\s*<([^>]+)>\s*$/);return bracket?{name:bracket[1].trim(),address:bracket[2].trim()}:{name:"",address:value.trim()};}return{name:text(value?.emailAddress?.name),address:text(value?.emailAddress?.address)};}
function main(workbook: ExcelScript.Workbook, messageJson: string): string {
  void workbook; const m=JSON.parse(messageJson) as MessageInput; const body=stripHtml(bodyContent(m.body)||text(m.bodyPreview)); const resumeText=text(m.attachmentText); const source=`${text(m.subject)}\n${body}\n${resumeText}`; const sender=mailbox(m.from||m.sender); const email=text(sender.address).toLowerCase(); const attachments=(m.attachments||[]).filter(a=>!a.isInline).map(a=>text(a.name||a.Name)); const resumes=attachments.filter(likelyResume);
  const github=urls(source,/(?:https?:\/\/|www\.)github\.com\/[A-Za-z0-9-]+(?:\/[A-Za-z0-9_.-]+)?/gi).filter(u=>!/github\.com\/(?:features|topics|organizations)(?:\/|$)/i.test(u)); const linkedin=urls(source,/https?:\/\/(?:www\.)?linkedin\.com\/in\/[A-Za-z0-9_%.-]+\/?/gi);
  const skills:{[key:string]:string}={Python:evidence(source,/\bpython\b/i),MachineLearning:evidence(source,/\bmachine\s+learning\b|\bML\b/i),DeepLearning:evidence(source,/\bdeep\s+learning\b/i),GenerativeAI:evidence(source,/\bgenerative\s+AI\b|\bgenai\b/i),LLM:evidence(source,/\bLLMs?\b|large\s+language\s+models?/i),RAG:evidence(source,/\bRAG\b|retrieval[- ]augmented\s+generation/i),AI_Agents:evidence(source,/\bAI\s+agents?\b|\bagentic\b/i),NLP:evidence(source,/\bNLP\b|natural\s+language\s+processing/i),ComputerVision:evidence(source,/\bcomputer\s+vision\b/i),FastAPI:evidence(source,/\bfastapi\b/i),LangChain:evidence(source,/\blangchain\b/i),PyTorch:evidence(source,/\bpytorch\b/i),TensorFlow:evidence(source,/\btensorflow\b/i),Git:evidence(source,/\bgit\b/i)};
  const scored=["Python","MachineLearning","DeepLearning","GenerativeAI","LLM","RAG","AI_Agents"]; let score=scored.reduce((n,k)=>n+(skills[k]==="Yes"?10:0),0); const reasons=scored.filter(k=>skills[k]==="Yes").map(k=>`${k}=10`); if(github.length){score+=10;reasons.push("GitHub=10");} if(/\b(project|built|developed|implemented|created)\b.{0,120}\b(ai|ml|rag|llm|chatbot|vision|nlp|model|agent)\b/i.test(source)){score+=10;reasons.push("RelevantProject=10");} if(/\b(B\.?Tech|M\.?Tech|B\.?E\.?|M\.?S\.?|computer science|artificial intelligence|data science|engineering)\b/i.test(source)){score+=10;reasons.push("RelevantEducation=10");}
  const phone=source.match(/(?:\+?\d[\d ()-]{7,}\d)/);const degree=firstMatch(source,[/\b(B\.?Tech|M\.?Tech|B\.?E\.?|M\.?E\.?|B\.?Sc|M\.?Sc|BCA|MCA|Ph\.?D|Bachelor(?:'s)?|Master(?:'s)?)\b/i]);const branch=firstMatch(source,[/\b(Computer Science(?: and Engineering)?|Information Technology|Artificial Intelligence(?: and Machine Learning)?|Data Science|Electronics(?: and Communication)?|Electrical Engineering|Mechanical Engineering)\b/i]);const college=firstMatch(source,[/\b([A-Z][A-Za-z&.' -]{2,70}(?:University|College|Institute of Technology|Institute))\b/]);const year=source.match(/\b(?:19|20)\d{2}\b/);const experience=firstMatch(source,[/\b(\d+(?:\.\d+)?)\+?\s*(?:years?|yrs?)\s+(?:of\s+)?experience\b/i]);const location=firstMatch(source,[/\b(?:current\s+)?location\s*[:\-]\s*([A-Za-z][A-Za-z ,.-]{1,60})/i,/\bbased\s+in\s+([A-Za-z][A-Za-z ,.-]{1,60})/i]);const role=firstMatch(source,[/\bcurrent\s+role\s*[:\-]\s*([A-Za-z][A-Za-z /&.-]{2,70})/i,/\bworking\s+as\s+(?:an?\s+)?([A-Za-z][A-Za-z /&.-]{2,70})/i]);const education=[degree,branch,college].filter(v=>v!=="").join(", ");const projects=conciseList(source,"projects?");const certifications=conciseList(source,"certifications?");
  const result:ApplicantPayload={Name:inferName(body,text(m.subject),text(sender.name),email),Email:email,Subject:text(m.subject),ReceivedDate:text(m.receivedDateTime),HasAttachment:attachments.length?"Yes":"No",Attachment:attachments.join(";"),GitHubLink:github.join(";"),LinkedInLink:linkedin.join(";"),Phone:phone?phone[0].trim():"",Location:location,Education:education,Degree:degree,Branch:branch,College:college,GraduationYear:year?year[0]:"",ExperienceYears:experience,CurrentRole:role,GitHubAvailable:github.length?"Yes":"No",Projects:projects,Certifications:certifications,ResumeAvailable:resumes.length?"Yes":"No",ResumeFileName:resumes.join(";"),ApplicationType:classify(source),InitialScreeningScore:Math.min(score,100),ScreeningStatus:"New",ScreeningNotes:reasons.length?`Initial score: ${reasons.join(", ")}`:"No scoring evidence found",MessageID:text(m.internetMessageId)||text(m.id),OutlookLink:text(m.webLink),ProcessedDate:new Date().toISOString(),...skills}; if(resumes.length&&!resumeText)result.ScreeningNotes=`${result.ScreeningNotes}; Resume parsing unavailable`; return JSON.stringify(result);
}
