const APPLICANT_HEADERS=["CandidateID","Name","Email","Subject","ReceivedDate","HasAttachment","Attachment","GitHubLink","LinkedInLink","Phone","Location","Education","Degree","Branch","College","GraduationYear","ExperienceYears","CurrentRole","Python","MachineLearning","DeepLearning","GenerativeAI","LLM","RAG","AI_Agents","NLP","ComputerVision","FastAPI","LangChain","PyTorch","TensorFlow","Git","GitHubAvailable","Projects","Certifications","ResumeAvailable","ResumeFileName","DuplicateFlag","ApplicationType","InitialScreeningScore","ScreeningStatus","ScreeningNotes","MessageID","OutlookLink","ProcessedDate"];
const MESSAGE_HEADERS=["CandidateID","MessageID","Subject","ReceivedDate","OutlookLink","DuplicateFlag"];
const LOG_HEADERS=["Timestamp","MessageID","Email","Status","Error","FlowName"];
interface Applicant {[key:string]:string|number|boolean|null|undefined}
interface UpsertResult {status:string;candidateId:string;duplicate:boolean;messageAlreadyProcessed:boolean}
function normalizedEmail(v:string):string{return v.trim().toLowerCase();}
function cell(v:string|number|boolean|null|undefined):string|number|boolean{return v===null||v===undefined?"":v;}
function ensureTable(w:ExcelScript.Workbook,sheetName:string,tableName:string,headers:string[]):ExcelScript.Table{let sheet=w.getWorksheet(sheetName);if(!sheet)sheet=w.addWorksheet(sheetName);let table=w.getTable(tableName);if(!table){const range=sheet.getRangeByIndexes(0,0,1,headers.length);range.setValues([headers]);table=sheet.addTable(range,true);table.setName(tableName);}const actual=table.getHeaderRowRange().getValues()[0].map(v=>String(v));if(actual.join("|")!==headers.join("|"))throw new Error(`${tableName} headers do not match the required schema.`);return table;}
function dataRows(t:ExcelScript.Table):(string|number|boolean)[][]{return t.getRowCount()===0?[]:t.getRangeBetweenHeaderAndTotal().getValues();}
function nextId(rows:(string|number|boolean)[][]):string{let max=0;rows.forEach(r=>{const m=String(r[0]).match(/^PAN-AI-(\d+)$/);if(m)max=Math.max(max,Number(m[1]));});return `PAN-AI-${String(max+1).padStart(4,"0")}`;}
function mergedApplicant(headers:string[],existing:(string|number|boolean)[],incoming:Applicant):(string|number|boolean)[]{const alwaysLatest:{[key:string]:boolean}={Subject:true,ReceivedDate:true,HasAttachment:true,Attachment:true,MessageID:true,OutlookLink:true,ProcessedDate:true,DuplicateFlag:true};return headers.map((header,column)=>{if(header==="CandidateID")return existing[column];if(header==="ScreeningStatus"&&String(existing[column]).trim()!=="")return existing[column];const next=cell(incoming[header]);if(alwaysLatest[header])return next;if(String(next).trim()!=="")return next;return existing[column];});}
function main(workbook:ExcelScript.Workbook,applicantJson:string,flowName:string="Power Automate"):UpsertResult{
 const applicant=JSON.parse(applicantJson) as Applicant;const applicants=ensureTable(workbook,"Applicants","Applicants",APPLICANT_HEADERS);const messages=ensureTable(workbook,"ApplicantMessages","ApplicantMessages",MESSAGE_HEADERS);const log=ensureTable(workbook,"ProcessingLog","ProcessingLog",LOG_HEADERS);applicants.getColumnByName("Phone").getRange().setNumberFormat("@");const aRows=dataRows(applicants);const mRows=dataRows(messages);const email=normalizedEmail(String(applicant.Email||""));const messageId=String(applicant.MessageID||"").trim();const seen=messageId!==""&&mRows.some(r=>String(r[1])===messageId);const index=email?aRows.findIndex(r=>normalizedEmail(String(r[2]))===email):-1;const candidateId=index>=0?String(aRows[index][0]):nextId(aRows);const duplicate=index>=0;applicant.CandidateID=candidateId;applicant.Email=email;applicant.DuplicateFlag=duplicate?"Yes":"No";applicant.ScreeningStatus=index>=0&&aRows[index][40]?aRows[index][40]:(applicant.ScreeningStatus||"New");
 try{if(!seen){const output=index>=0?mergedApplicant(APPLICANT_HEADERS,aRows[index],applicant):APPLICANT_HEADERS.map(h=>cell(applicant[h]));if(index>=0)applicants.getRangeBetweenHeaderAndTotal().getRow(index).setValues([output]);else applicants.addRow(-1,output);messages.addRow(-1,[candidateId,messageId,cell(applicant.Subject),cell(applicant.ReceivedDate),cell(applicant.OutlookLink),duplicate?"Yes":"No"]);}const status=seen?"Skipped":(duplicate?"Duplicate":"Success");log.addRow(-1,[new Date().toISOString(),messageId,email,status,"",flowName]);return{status,candidateId,duplicate,messageAlreadyProcessed:seen};}catch(error){const detail=error instanceof Error?error.message:String(error);log.addRow(-1,[new Date().toISOString(),messageId,email,"Failed",detail,flowName]);throw error;}
}
